import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const WelcomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFF8E7",
  },
  floatingElement: {
    position: "absolute",
    borderRadius: 75,
    opacity: 0.7,
  },
  floatingElement1: {
    width: 150,
    height: 150,
    backgroundColor: "#FFD1DC",
    top: -30,
    left: -40,
  },
  floatingElement2: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#B5EAD7",
    bottom: 80,
    right: 20,
  },
  floatingElement3: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#C7CEEA",
    bottom: 200,
    left: 40,
  },
  floatingElement4: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FFDAC1",
    top: height * 0.3,
    right: 30,
  },
  scrollContainer: {
    padding: 20,
    paddingBottom: 100,
  },
  header: {
    alignItems: "center",
    marginTop: 40,
  },
  mascotImage: {
    width: width * 0.35,
    height: width * 0.35,
    marginBottom: 15,
  },
  welcomeTextContainer: {
    alignItems: "center",
  },
  greetingText: {
    fontSize: 22,
    fontFamily: "OpenDyslexic",
    color: "#FF6B6B",
  },
  welcomeTitle: {
    fontSize: 28,
    fontWeight: "bold",
    fontFamily: "OpenDyslexic",
    marginVertical: 8,
    textAlign: "center",
    color: "#4A4A4A",
  },
  welcomeSubtitle: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
    lineHeight: 22,
  },
  statsCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    marginTop: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 2,
    borderColor: "#F0F0F0",
  },
  statsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  statsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#4A4A4A",
    fontFamily: "OpenDyslexic",
  },
  spinningStar: {
    fontSize: 20,
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  statItem: {
    alignItems: "center",
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#F8F9FA",
    minWidth: 80,
  },
  statNumber: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#FF6B6B",
    fontFamily: "OpenDyslexic",
  },
  statLabel: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
    marginTop: 4,
    fontFamily: "OpenDyslexic",
  },
  actionButtonsContainer: {
    marginTop: 25,
  },
  mainActionButton: {
    borderRadius: 16,
    marginBottom: 15,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonGradient: {
    flexDirection: "row",
    alignItems: "center",
    padding: 18,
    justifyContent: "space-between",
  },
  buttonEmoji: {
    fontSize: 28,
  },
  buttonTextContainer: {
    flex: 1,
    marginLeft: 15,
  },
  mainButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    fontFamily: "OpenDyslexic",
  },
  mainButtonSubtitle: {
    fontSize: 13,
    color: "#f1f1f1",
    marginTop: 2,
    fontFamily: "OpenDyslexic",
  },
  arrow: {
    fontSize: 18,
    opacity: 0.8,
  },
  toolsContainer: {
    marginTop: 25,
  },
  toolsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 15,
    color: "#4A4A4A",
    fontFamily: "OpenDyslexic",
  },
  toolsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  toolButton: {
    alignItems: "center",
    padding: 15,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    minWidth: 85,
  },
  toolEmoji: {
    fontSize: 28,
    marginBottom: 5,
  },
  toolLabel: {
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
    color: "#4A4A4A",
    fontFamily: "OpenDyslexic",
  },
  challengeCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    marginTop: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    borderWidth: 2,
    borderColor: "#E0E7FF",
  },
  challengeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  challengeTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#4A4A4A",
    fontFamily: "OpenDyslexic",
  },
  challengeBadge: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#FF6B6B",
    fontFamily: "OpenDyslexic",
  },
  challengeSubtitle: {
    fontSize: 14,
    color: "#666",
    marginBottom: 20,
    lineHeight: 20,
    fontFamily: "OpenDyslexic",
  },
  challengeButton: {
    borderRadius: 12,
    overflow: "hidden",
  },
  challengeButtonGradient: {
    padding: 14,
    alignItems: "center",
  },
  challengeButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 15,
    fontFamily: "OpenDyslexic",
  },
  footer: {
    alignItems: "center",
    marginTop: 25,
    padding: 20,
  },
  footerText: {
    fontSize: 15,
    color: "#888",
    fontStyle: "italic",
    fontFamily: "OpenDyslexic",
  },
  streakCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    marginTop: 25,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    marginBottom: 20,
  },
  streakTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#394693",
    marginBottom: 5,
  },
  streakNumber: {
    fontSize: 48,
    fontWeight: "bold",
    color: "#6C63FF",
    marginVertical: 5,
  },
  streakButton: {
    backgroundColor: "#FFD700",
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginTop: 10,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  streakButtonText: {
    color: "#394693",
    fontSize: 16,
    fontWeight: "bold",
  },
  errorText: {
    color: "#EF4444",
    textAlign: "center",
    marginBottom: 10,
  },
});

export default WelcomeStyles;