import { StyleSheet, Platform } from "react-native";

const styles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    backgroundColor: "#F2F8FF",
  },
  innerContainer: {
    padding: 24,
    paddingBottom: 50,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 40,
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  logoIcon: {
    width: 56,
    height: 56,
    backgroundColor: "#6C63FF",
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    transform: [{ rotate: "5deg" }],
  },
  logoIconText: {
    fontSize: 32,
    color: "#fff",
  },
  logoText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#394693",
    marginLeft: 10,
  },
  audioButton: {
    padding: 12,
    backgroundColor: "#fff",
    borderRadius: 16,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  heroSection: {
    alignItems: "center",
    marginBottom: 40,
  },
  heroTitle: {
    fontSize: 48,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 10,
    lineHeight: 60,
  },
  heroSubtitle: {
    fontSize: 18,
    color: "#666",
    textAlign: "center",
    lineHeight: 28,
  },
  mascotArea: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 40,
  },
  mascotButton: {
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "#AEE7F8",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 8,
  },
  mascotEmoji: {
    fontSize: 100,
  },
  spinnerContainer: {
    backgroundColor: "rgba(0,0,0,0.4)",
    borderRadius: 100,
    justifyContent: "center",
    alignItems: "center",
  },
  greetingBox: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 15,
    marginTop: 20,
    width: "90%",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    flexDirection: "row",
    alignItems: "center",
  },
  greetingIconContainer: {
    backgroundColor: "#6C63FF",
    borderRadius: 20,
    padding: 5,
    marginRight: 10,
  },
  greetingText: {
    fontSize: 16,
    color: "#394693",
    textAlign: "center",
    flex: 1,
  },
  authContainer: {
    marginBottom: 40,
    paddingHorizontal: Platform.OS === 'web' ? '20%' : 0,
  },
  formToggleContainer: {
    flexDirection: "row",
    backgroundColor: "#E5E7EB",
    borderRadius: 12,
    marginBottom: 20,
    padding: 5,
  },
  formToggleButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
  },
  formToggleButtonActive: {
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  formToggleButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6B7280",
  },
  formToggleButtonTextActive: {
    color: "#394693",
  },
  formSection: {
    width: "100%",
    alignItems: "center",
  },
  formTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#394693",
    marginBottom: 20,
    textAlign: "center",
  },
  input: {
    width: "100%",
    padding: 15,
    backgroundColor: "#fff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 15,
    fontSize: 16,
    color: "#333",
  },
  consentContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    paddingHorizontal: 10,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: "#6C63FF",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  checkmark: {
    color: "#6C63FF",
    fontSize: 16,
  },
  consentText: {
    fontSize: 14,
    color: "#666",
    flex: 1,
    flexWrap: 'wrap',
  },
  linkText: {
    color: "#6C63FF",
    textDecorationLine: "underline",
  },
  errorText: {
    color: "#EF4444",
    textAlign: "center",
    marginBottom: 10,
  },
  submitButton: {
    width: "100%",
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#34D399",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
  },
  submitButtonText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  ctaButtonContainer: {
    width: "100%",
    alignItems: "center",
    marginBottom: 40,
  },
  ctaButton: {
    backgroundColor: "#34D399",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 14,
    width: "80%",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 10,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
  },
  ctaButtonText: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "bold",
  },
  ctaButtonContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  sectionContainer: {
    marginBottom: 40,
  },
  sectionHeader: {
    alignItems: "center",
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#394693",
    marginBottom: 10,
    textAlign: "center",
  },
  sectionSubtitle: {
    fontSize: 16,
    color: "#666",
    textAlign: "center",
    maxWidth: 600,
  },
  powersGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-around",
  },
  powerCard: {
    width: "30%",
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 15,
    margin: 5,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  powerIconContainer: {
    marginBottom: 10,
  },
  powerIcon: {
    fontSize: 50,
  },
  powerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#394693",
    textAlign: "center",
  },
  powerSubtitle: {
    fontSize: 12,
    color: "#6C63FF",
    textAlign: "center",
    marginBottom: 10,
  },
  powerDescription: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
  },
  activitiesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-around",
  },
  activityCard: {
    width: "22%",
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 10,
    margin: 5,
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
  },
  activityIcon: {
    fontSize: 30,
    marginBottom: 5,
  },
  activityTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#394693",
    textAlign: "center",
  },
  activitySubtitle: {
    fontSize: 10,
    color: "#6C63FF",
    textAlign: "center",
  },
  encouragementContainer: {
    backgroundColor: "#E3ECFB",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
  },
  encouragementText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#394693",
    marginBottom: 5,
  },
  encouragementSubtitle: {
    fontSize: 16,
    color: "#666",
    marginBottom: 20,
    textAlign: "center",
  },
  encouragementButton: {
    backgroundColor: "#FFD700",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 3,
  },
  encouragementButtonText: {
    color: "#394693",
    fontSize: 18,
    fontWeight: "bold",
  },
});

export default styles;