import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    centered: {
        justifyContent: "center",
        alignItems: "center",
    },
    scrollContent: {
        padding: 20,
        alignItems: "center",
        paddingBottom: 40,
    },
    header: {
        alignItems: "center",
        marginBottom: 20,
    },
    title: {
        fontSize: 28,
        color: "#6A1B9A",
        textAlign: "center",
        textShadow: "2px 2px 8px rgba(255, 255, 255, 0.8)", // ⚠️ Not supported in RN, use shadow props instead
        marginBottom: 10,
    },
    statusRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 5,
    },
    difficultyBadge: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 15,
        marginRight: 10,
    },
    modeBadge: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 15,
    },
    easyBadge: {
        backgroundColor: "#4CAF50",
    },
    mediumBadge: {
        backgroundColor: "#FF9800",
    },
    hardBadge: {
        backgroundColor: "#F44336",
    },
    difficultyText: {
        color: "#fff",
        fontWeight: "bold",
        fontSize: 12,
    },
    modeText: {
        color: "#fff",
        fontWeight: "bold",
        fontSize: 12,
    },
    ttsStatus: {
        fontSize: 12,
        color: "#666",
        fontStyle: "italic",
    },
    modeContainer: {
        width: "100%",
        marginBottom: 20,
        alignItems: "center",
    },
    modeTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
        marginBottom: 10,
    },
    modeButtons: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "center",
    },
    modeButton: {
        paddingHorizontal: 15,
        paddingVertical: 8,
        borderRadius: 20,
        margin: 5,
        // ❌ boxShadow not supported in RN → use shadow/elevation
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    activeModeButton: {
        borderWidth: 3,
        borderColor: "#FFD700",
    },
    modeButtonText: {
        color: "#fff",
        fontWeight: "bold",
        fontSize: 14,
    },
    progressContainer: {
        backgroundColor: "#E8F5E8",
        padding: 10,
        borderRadius: 15,
        marginBottom: 15,
    },
    progressText: {
        color: "#4CAF50",
        fontWeight: "bold",
        textAlign: "center",
    },
    controlsContainer: {
        width: "100%",
        marginBottom: 20,
        alignItems: "center",
    },
    featureButton: {
        backgroundColor: "#9C27B0",
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
        marginBottom: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    activeFeature: {
        backgroundColor: "#E91E63",
    },
    featureButtonText: {
        color: "#fff",
        fontWeight: "bold",
        fontSize: 16,
    },
    stopButton: {
        backgroundColor: "#F44336",
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    stopButtonText: {
        color: "#fff",
        fontWeight: "bold",
        fontSize: 16,
    },
    poemContainer: {
        marginBottom: 30,
        width: "100%",
    },
    lineContainer: {
        marginBottom: 12,
    },
    lineWrapper: {
        flexDirection: "row",
        paddingVertical: 10,
        paddingHorizontal: 8,
        borderRadius: 8,
        alignItems: "flex-start",
    },
    lineNumber: {
        fontSize: 14,
        color: "#999",
        marginRight: 8,
        minWidth: 25,
        textAlign: "right",
    },
    completedIcon: {
        fontSize: 16,
        marginRight: 5,
    },
    wordsContainer: {
        flex: 1,
        flexDirection: "row",
        flexWrap: "wrap",
        alignItems: "center",
    },
    wordTouchable: {
        marginRight: 4,
        marginBottom: 2,
    },
    word: {
        fontSize: 18,
        color: "#333",
        paddingHorizontal: 3,
        paddingVertical: 2,
        borderRadius: 4,
    },
    chooseText: {
        fontSize: 22,
        fontWeight: "bold",
        marginBottom: 15,
        color: "#FF5722",
    },
    card: {
        width: "90%",
        padding: 15,
        borderRadius: 20,
        backgroundColor: "#fff",
        marginBottom: 12,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    selectedCard: {
        backgroundColor: "#FFD54F",
        transform: [{ scale: 1.02 }],
        borderWidth: 2,
        borderColor: "#FF9800",
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#3F51B5",
        marginBottom: 5,
    },
    cardTheme: {
        fontSize: 14,
        color: "#666",
        marginBottom: 8,
    },
    miniDifficultyBadge: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 10,
    },
    miniDifficultyText: {
        color: "#fff",
        fontWeight: "bold",
        fontSize: 10,
    },
    quizContainer: {
        width: "100%",
        backgroundColor: "#fff",
        padding: 20,
        borderRadius: 15,
        marginBottom: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    quizTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#3F51B5",
        marginBottom: 10,
        textAlign: "center",
    },
    quizQuestion: {
        fontSize: 18,
        color: "#333",
        marginBottom: 15,
        fontFamily: "OpenDyslexic",
    },
    quizOptionButton: {
        backgroundColor: "#E0F7FA",
        padding: 10,
        borderRadius: 10,
        marginBottom: 10,
    },
    quizOptionText: {
        fontSize: 16,
        color: "#333",
        textAlign: "center",
        fontFamily: "OpenDyslexic",
    },
    quizScore: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#4CAF50",
        textAlign: "center",
        marginTop: 10,
    },
    recordingContainer: {
        width: "100%",
        backgroundColor: "#fff",
        padding: 15,
        borderRadius: 15,
        marginBottom: 20,
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    recordingPrompt: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#333",
        marginBottom: 10,
    },
    recordingLine: {
        fontSize: 16,
        color: "#333",
        marginBottom: 15,
        fontFamily: "OpenDyslexic",
        textAlign: "center",
    },
    recordingButton: {
        backgroundColor: "#2196F3",
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
    },
    stopRecordingButton: {
        backgroundColor: "#F44336",
    },
    recordingButtonText: {
        color: "#fff",
        fontWeight: "bold",
        fontSize: 16,
    },
    feedbackContainer: {
        marginTop: 15,
        alignItems: "center",
    },
    feedbackText: {
        fontSize: 14,
        color: "#333",
        marginBottom: 5,
    },
    // 🔥 Debug panel styles
    debugPanel: {
        position: "absolute",
        top: 100,
        right: 10,
        backgroundColor: "rgba(0,0,0,0.9)",
        padding: 15,
        borderRadius: 10,
        zIndex: 1000,
        minWidth: 200,
    },
    debugTitle: {
        color: "white",
        fontSize: 16,
        fontWeight: "bold",
        marginBottom: 10,
        textAlign: "center",
    },
    debugStatus: {
        color: "white",
        fontSize: 12,
        marginBottom: 10,
        textAlign: "center",
    },
    debugButton: {
        backgroundColor: "#4CAF50",
        padding: 8,
        borderRadius: 5,
        marginBottom: 5,
        alignItems: "center",
    },
    debugTrigger: {
        position: "absolute",
        top: 50,
        right: 10,
        backgroundColor: "orange",
        padding: 5,
        borderRadius: 5,
        zIndex: 999,
    },
    // 🔥 Loading overlay
    loadingOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.5)",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1000,
    },
    loadingText: {
        color: "white",
        marginTop: 10,
        fontSize: 16,
    },

    recordingContainer: {
        backgroundColor: "white",
        padding: 15,
        borderRadius: 10,
        marginVertical: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    recordingPrompt: {
        fontSize: 16,
        fontWeight: "bold",
        marginBottom: 10,
        textAlign: "center",
    },
    recordingLine: {
        fontSize: 18,
        fontStyle: "italic",
        textAlign: "center",
        marginBottom: 15,
        lineHeight: 24,
    },
    recordingButton: {
        backgroundColor: "#FF9800",
        padding: 15,
        borderRadius: 8,
        alignItems: "center",
        marginVertical: 5,
    },
    stopRecordingButton: {
        backgroundColor: "#F44336",
    },
    disabledButton: {
        backgroundColor: "#cccccc",
    },
    recordingButtonText: {
        color: "white",
        fontWeight: "bold",
        fontSize: 16,
    },
    repeatButton: {
        backgroundColor: "#2196F3",
        padding: 15,
        borderRadius: 8,
        alignItems: "center",
        marginVertical: 5,
    },
    repeatButtonText: {
        color: "white",
        fontWeight: "bold",
        fontSize: 16,
    },
    feedbackContainer: {
        marginTop: 15,
        padding: 10,
        backgroundColor: "#f5f5f5",
        borderRadius: 8,
    },
    feedbackText: {
        fontSize: 14,
        marginBottom: 5,
    },

});

export default styles;